[project]
name = "speckle-auth"
version = "0.1.0"
description = "Speckle authentication app using Streamlit"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "streamlit>=1.40.0",
    "requests>=2.32.0",
    "python-dotenv>=1.0.0",
    "flask>=3.1.2",
]
